---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meanapp
  labels:
    app: meanapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meanapp
  template:
    metadata:
      labels:
        app: meanapp
    spec:
      restartPolicy: Always
      containers:
        - name: meanapp
          image: minhtrietbkit/mean-stack-angular-7-crud-app-example:latest
          env:
            - name: DB_HOST
              value: "mongo.default.svc.cluster.local"
          ports:
            - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: meanapp
spec:
  selector:
    app: meanapp
  ports:
    - port: 4000
      targetPort: 4000
