---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lampapp
  labels:
    app: lampapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lampapp
  template:
    metadata:
      labels:
        app: lampapp
    spec:
      restartPolicy: Always
      containers:
        - name: lampapp
          image: minhtrietbkit/lamp-app:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lampapp
spec:
  selector:
    app: lampapp
  ports:
    - port: 80
      targetPort: 80
